Pay for plans
just1and0/React-Native-Paystack-WebView pull request #135
Opened 2023-03-16 09:56 UTC by Fiyifoluwa

adjusted types as well as Paystack.tsx

2024-02-20 21:22 UTC, just1and0 requested changes

2024-02-20 21:22 UTC, just1and0 commented on src/paystack.tsx
> +  const paystackPlan = (!plan || plan == null || plan == undefined) ? '' : `plan: '${plan}',`;
please follow pattern  => plan ? `plan: '${plan}',` :  ' ';

2024-08-07 08:58 UTC, Fiyifoluwa commented on src/paystack.tsx
> +  const paystackPlan = (!plan || plan == null || plan == undefined) ? '' : `plan: '${plan}',`;
these changes have been made

2024-11-04 21:53 UTC, just1and0 commented
available on v4

2024-11-04 21:53 UTC, closed without merging