Added split/subaccount payment feature
just1and0/React-Native-Paystack-WebView pull request #138
Opened 2023-09-01 12:57 UTC by GenerousDev

2024-02-20 21:10 UTC, just1and0 commented
@GenerousDev I see you included your details in the .all-contributorsrc file. This should not be so. This file is auto-generated once your PR is approved by an admin.

Could you remove the changes made to this file so we can review your PR?

2024-02-20 21:11 UTC, just1and0 requested changes

2024-02-20 21:11 UTC, just1and0 commented on .all-contributorsrc
> +    {
@GenerousDev I see you included your details in the .all-contributorsrc file. This should not be so. This file is auto-generated once your PR is approved by an admin.

Could you remove the changes made to this file so we can review your PR?

2024-05-23 17:17 UTC, opmat reviewed
Subaccount payment feature has already been added on version 4.0.4 from [commit 6ac4a80](https://github.com/just1and0/React-Native-Paystack-WebView/commit/6ac4a803259960ba76226ab82ba8993397c853da)

2024-11-04 21:54 UTC, just1and0 commented
done on v4

2024-11-04 21:54 UTC, closed without merging