Update README and paystack component for improved installation instructions and code consistency
just1and0/React-Native-Paystack-WebView pull request #173
Opened 2024-10-09 21:22 UTC by Darkace01

This pull request includes updates to the `README.md` file and various improvements to the `development/paystack.tsx` file. The changes enhance installation instructions, update usage examples, and improve code readability and type safety.

### Documentation Updates:

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L17-R75): Enhanced installation instructions for both npm and yarn, and added specific instructions for Expo installations.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L76-R105): Clarified usage examples, including the use of refs.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L129-R162): Updated the contributions section to encourage community involvement and updated the licensing information. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L129-R162) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L147-R177)
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R218-R226): Added a roadmap section outlining future improvements.

### Code Improvements:

* [`development/paystack.tsx`](diffhunk://#diff-0fc96720264630b6647c804a114b3d7e7ee9b4f068f1f5129b17e1bcce15dad4L1-R7): Improved type safety by using `import type` for TypeScript imports and specified types for `channels` and other variables. [[1]](diffhunk://#diff-0fc96720264630b6647c804a114b3d7e7ee9b4f068f1f5129b17e1bcce15dad4L1-R7) [[2]](diffhunk://#diff-0fc96720264630b6647c804a114b3d7e7ee9b4f068f1f5129b17e1bcce15dad4L19-R20)
* [`development/paystack.tsx`](diffhunk://#diff-0fc96720264630b6647c804a114b3d7e7ee9b4f068f1f5129b17e1bcce15dad4L31-R33): Renamed state variables to follow camelCase convention. [[1]](diffhunk://#diff-0fc96720264630b6647c804a114b3d7e7ee9b4f068f1f5129b17e1bcce15dad4L31-R33) [[2]](diffhunk://#diff-0fc96720264630b6647c804a114b3d7e7ee9b4f068f1f5129b17e1bcce15dad4L41-R51) [[3]](diffhunk://#diff-0fc96720264630b6647c804a114b3d7e7ee9b4f068f1f5129b17e1bcce15dad4L114-R120) [[4]](diffhunk://#diff-0fc96720264630b6647c804a114b3d7e7ee9b4f068f1f5129b17e1bcce15dad4L142-R144) [[5]](diffhunk://#diff-0fc96720264630b6647c804a114b3d7e7ee9b4f068f1f5129b17e1bcce15dad4L155-R158)
* [`development/paystack.tsx`](diffhunk://#diff-0fc96720264630b6647c804a114b3d7e7ee9b4f068f1f5129b17e1bcce15dad4L87-R88): Used template literals for string interpolation to improve readability.
* [`development/paystack.tsx`](diffhunk://#diff-0fc96720264630b6647c804a114b3d7e7ee9b4f068f1f5129b17e1bcce15dad4L174-L177): Removed unnecessary blank lines at the end of the file.

2024-10-13 00:48 UTC, mosoakinyemi commented
Code changes LGTM! 
Might wanna align w/ @just1and0 for the doc changes.

cc @just1and0

2024-10-13 17:31 UTC, Darkace01 commented
> Code changes LGTM! Might wanna align w/ @just1and0 for the doc changes.
> 
> cc @just1and0

Alright thanks

2024-10-13 19:30 UTC, just1and0 requested changes

2024-10-13 19:30 UTC, just1and0 commented on README.md
> +Want to help make this package even more awesome? [Read how to contribute](https://github.com/just1and0/React-Native-Paystack-WebView/blob/master/CONTRIBUTING.md) and feel free to send in your PR!
Your url still points to master and not main.

2024-10-13 19:30 UTC, just1and0 commented on README.md
> -A huge shoutout to our amazing contributors! Your efforts make this project better every day. Check out the ([emoji key](https://allcontributors.org/docs/en/emoji-key)) for what each contribution mea
Most of the changes you made to this isn't necessary, you are changing titles and descriptions which has nothing to do with improvements. Your change should only affect the improvement to code you are trying to make.


Also I think this PR might be boasted, it carries to many changes from code to docs. Can you make this more streamlined?

2025-01-13 15:13 UTC, just1and0 commented
stale work.

2025-01-13 15:13 UTC, closed without merging